name: SCA - Check Dependencies
on:
  pull_request:
    types: [opened, reopened]
permissions:
  pull-requests: write
jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
     - name: Action for Dependency Scanning
       uses: actions/dependency-review-action@v4.1.3
       with:
         fail-on-severity: high
         fail-on-scopes: runtime
         vulnerability-check: true
         license-check: true
