name: CI

on: [push]

jobs:
  sast_scan:
    name: Run CodeQL Scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'python'
        
    - name: Perform Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:{{matrix.language}}"

  dast_scan:
    runs-on: ubuntu-latest
    name: Scan a vulnerable app from the web
    steps:
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        
